// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAnnouncementReadRecord = "announcement_read_record"

// AnnouncementReadRecord 记录用户是否阅读某一条公告
type AnnouncementReadRecord struct {
	ID             int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	UserID         string `gorm:"column:user_id;type:varchar(50);not null;comment:用户的userid" json:"userId"`    // 用户的userid
	AnnouncementID int64  `gorm:"column:announcement_id;type:int;not null;comment:公告id" json:"announcementId"` // 公告id
}

// TableName AnnouncementReadRecord's table name
func (*AnnouncementReadRecord) TableName() string {
	return TableNameAnnouncementReadRecord
}
