// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAnnouncement = "announcements"

// Announcement mapped from table <announcements>
type Announcement struct {
	ID          int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	AdminID     int64     `gorm:"column:admin_id;type:int;not null" json:"adminId"`
	Title       string    `gorm:"column:title;type:varchar(100);not null" json:"title"`
	Content     string    `gorm:"column:content;type:text;not null" json:"content"`
	PublishTime time.Time `gorm:"column:publish_time;type:timestamp;default:CURRENT_TIMESTAMP" json:"publishTime"`
}

// TableName Announcement's table name
func (*Announcement) TableName() string {
	return TableNameAnnouncement
}
