// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDayReviewStatistic = "day_review_statistics"

// DayReviewStatistic 用户每天的复习情况记录
type DayReviewStatistic struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	CardNum    int64     `gorm:"column:card_num;type:int;not null;comment:当天复习了多少张卡片" json:"cardNum"`      // 当天复习了多少张卡片
	EasyNum    int64     `gorm:"column:easy_num;type:int;not null;comment:复习时选择easy的次数" json:"easyNum"`    // 复习时选择easy的次数
	GoodNum    int64     `gorm:"column:good_num;type:int;not null;comment:复习时选择good的次数" json:"goodNum"`    // 复习时选择good的次数
	AgainNum   int64     `gorm:"column:again_num;type:int;not null;comment:复习时选择again的次数" json:"againNum"` // 复习时选择again的次数
	HardNum    int64     `gorm:"column:hard_num;type:int;not null;comment:复习时选择hard的次数" json:"hardNum"`    // 复习时选择hard的次数
	RecordDate time.Time `gorm:"column:record_date;type:date;not null;comment:是哪一天" json:"recordDate"`     // 是哪一天
	UserID     string    `gorm:"column:user_id;type:varchar(50);not null;comment:用户的id" json:"userId"`     // 用户的id
}

// TableName DayReviewStatistic's table name
func (*DayReviewStatistic) TableName() string {
	return TableNameDayReviewStatistic
}
