// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDeck = "decks"

// Deck mapped from table <decks>
type Deck struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt    time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Name         string         `gorm:"column:name;type:longtext" json:"name"`
	Cardnum      int64          `gorm:"column:cardnum;type:bigint" json:"cardnum"`
	Learnnumber  int64          `gorm:"column:learnnumber;type:bigint" json:"learnnumber"`
	Introduction string         `gorm:"column:introduction;type:longtext" json:"introduction"`
	Floderid     int64          `gorm:"column:floderid;type:bigint" json:"floderid"`
	UserID       int64          `gorm:"column:user_id;type:int" json:"userId"`
}

// TableName Deck's table name
func (*Deck) TableName() string {
	return TableNameDeck
}
