// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID             int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt      time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Gender         int64          `gorm:"column:gender;type:bigint;comment:性别" json:"gender"` // 性别
	Age            int64          `gorm:"column:age;type:bigint" json:"age"`
	Password       string         `gorm:"column:password;type:longtext" json:"password"`
	HeadURL        string         `gorm:"column:head_url;type:longtext;comment:头像" json:"headUrl"` // 头像
	Email          string         `gorm:"column:email;type:longtext" json:"email"`
	Username       string         `gorm:"column:username;type:longtext;comment:登录的用户名" json:"username"` // 登录的用户名
	Introduction   string         `gorm:"column:introduction;type:longtext" json:"introduction"`
	Learnnumoneday int64          `gorm:"column:learnnumoneday;type:bigint;comment:一天学多少" json:"learnnumoneday"` // 一天学多少
	UserID         string         `gorm:"column:user_id;type:varchar(191)" json:"userId"`
	Nickname       string         `gorm:"column:nickname;type:varchar(20)" json:"nickname"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
