// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: train_sever.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrainerClient is the client API for Trainer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainerClient interface {
	TrainWeights(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainReply, error)
}

type trainerClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainerClient(cc grpc.ClientConnInterface) TrainerClient {
	return &trainerClient{cc}
}

func (c *trainerClient) TrainWeights(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainReply, error) {
	out := new(TrainReply)
	err := c.cc.Invoke(ctx, "/Trainer/TrainWeights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainerServer is the server API for Trainer service.
// All implementations must embed UnimplementedTrainerServer
// for forward compatibility
type TrainerServer interface {
	TrainWeights(context.Context, *TrainRequest) (*TrainReply, error)
	mustEmbedUnimplementedTrainerServer()
}

// UnimplementedTrainerServer must be embedded to have forward compatible implementations.
type UnimplementedTrainerServer struct {
}

func (UnimplementedTrainerServer) TrainWeights(context.Context, *TrainRequest) (*TrainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainWeights not implemented")
}
func (UnimplementedTrainerServer) mustEmbedUnimplementedTrainerServer() {}

// UnsafeTrainerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainerServer will
// result in compilation errors.
type UnsafeTrainerServer interface {
	mustEmbedUnimplementedTrainerServer()
}

func RegisterTrainerServer(s grpc.ServiceRegistrar, srv TrainerServer) {
	s.RegisterService(&Trainer_ServiceDesc, srv)
}

func _Trainer_TrainWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServer).TrainWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Trainer/TrainWeights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServer).TrainWeights(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trainer_ServiceDesc is the grpc.ServiceDesc for Trainer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trainer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Trainer",
	HandlerType: (*TrainerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrainWeights",
			Handler:    _Trainer_TrainWeights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "train_sever.proto",
}
