env: prod
http:
  host: 0.0.0.0
  port: 8003
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  mysql:
    user: root:peifeng@tcp(peifeng.site:3306)/spacere?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: peifeng.site:6379
    password: ningzaichun
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: info
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true